version: "3.1"

services:
  n8n:
    image: n8nio/n8n:0.134.0
    ports:
      - 5678:5678
    environment:
      - TZ=Asia/Tokyo
      - GENERIC_TIMEZONE=Asia/Tokyo
      - NODE_ENV=production
      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=5678
      - WEBHOOK_URL=http://${DOMAIN_NAME}${N8N_PATH}
    volumes:
      - ./data:/home/node/.n8n
