version: "3.1"

services:
  n8n:
    image: n8nio/n8n:0.134.0
    ports:
      - ${N8N_PORT}:${N8N_PORT}
    environment:
      - N8N_HOST=${DOMAIN_NAME}
      - WEBHOOK_URL=https://${DOMAIN_NAME}/${N8N_PATH}
    volumes:
      - ./data:/home/node/.n8n
