version: "3.1"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - 5678:5678
    environment:
      - NODE_ENV=production
      - N8NBASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=5678
      - WEBHOOK_URL=http://${DOMAIN_NAME}${N8N_PATH}
    volumes:
      - ./data:/home/node/.n8n
